export const metadata = {
  title: "Aayush Singh Tomar - Full Stack Developer",
  description: "Generated by create next app",
};

import HeroMain from "@/components/HeroMain";
import React from "react";

const page = () => {
  return (
    <>
      <HeroMain />
    </>
  );
};

export default page;
